### ISSUE TITLE
CiPA 코드 실행 시 오류 보고

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/book-cipa#1]
가톨릭대 연구조교수 한성필입니다. CiPA 코드 실행 시 오류 보고를 국내에서 할 수 있는 공간을 만들었습니다.

@platanus-study 선생님, https://github.com/FDA/CiPA/issues 에 글 남기신 것 보았습니다. 저 말고는 아무도 답변을 안달고 있는데, 혹시 이곳이 편하시면 질문글 남겨주세요. 저희 팀에서 지난 2년간 CiPA 코드와 ecglib 코드를 모두 실행해본 경험이 있습니다. 

아래 자료도 참고해주세요.

[독성] 의약품 심장독성 스크리닝 기술 동향 정보집, 임상연구과 (2020) https://www.nifds.go.kr/brd/m_18/view.do?seq=12505

**Comment by platanus-study** [comment]
Issue 1 - Hill fitting 폴더에 포함된  IC50_mcmc.R 코드경로 및 컴파일 에러

       1. 데이터 경로 설정 문제
       # read in patch clamp data
       datadf<-read.csv(datafile)
       datadf<-datadf[datadf$drug==drug,]
       datadf<-datadf[with(datadf,order(drug,conc,channel)),]

       2. IC50_mcmc.R을 컴파일을 한 후 발생하는 에러
      
        [Error example 1]
       -에러와 관련된 R 코드 부분
       #--- required argument
       if(is.null(args$drug)) stop("Missing drug argument!")
       drug<-args$drug
       
       - 컴파일 결과
       > #--- required argument
       > if(is.null(args$drug)) stop("Missing drug argument!")
          에러: Missing drug argument!
        > drug<-args$drug

       [Error example 2]
       -에러와 관련된 R 코드 부분
       # save samples to table
       drugdir<-sprintf("results/%s/",drug)
       system(paste0("mkdir -p ",drugdir))
       
       -컴파일 결과 발생하는 에러
       > # save samples to table
       > drugdir<-sprintf("results/%s/",drug)
       > system(paste0("mkdir -p ",drugdir))
         /Rtools/bin/mkdir: missing operand
       Try '/Rtools/bin/mkdir --help' for more information.
       [1] 1

* 문의사항
 
<1>데이터 경로 설정 문제 : datadf<-read.csv(datafile)라고 나타내고 있지만, datafile 경로에 어떤 파일을 포함해야 하는지 모르겠습니다. 명확한 파일명을 알려주셨으면 합니다.

<2>IC50_mcmc.R을 컴파일을 한 후 발생하는 에러 문제: 
 위에서 언급한 '2. [Error example 1]과 [Error example 2]' 부분과 관련한 에러는 read.csv(datafile)에 명확한 데이터 경로를 제시하지 않아 발생한 에러인 것 같습니다.  만약 문제가 다른 원인에 있다면, 해결방법을 알려주시기를 부탁드립니다.
